export const PROMPTS: string[] = [
  "The last train out of the city is boarding, but you don't have a ticket.",
  "A stranger hands you a key and whispers, 'Don't let them find it.'",
  "You wake up and everyone in the world has vanished, except for one other person.",
  "Write about a memory that you've never actually experienced.",
  "A door appears in your living room that wasn't there yesterday.",
  "Describe the feeling of falling without ever hitting the ground.",
  "The stars in the night sky begin to spell out a message.",
  "You find a letter addressed to you, dated 50 years in the future.",
  "A quiet evening turns into a fight for survival.",
  "Write about a character who discovers they are a character in a book.",
  "The ocean suddenly recedes, revealing an ancient city.",
  "You receive a phone call from someone who claims to be your past self.",
  "A watch that counts down the time left until a mysterious event.",
  "Describe a world where music is illegal.",
  "A reflection in the mirror does something you didn't do.",
  "The first manned mission to Mars discovers something impossible.",
  "Write about a secret society that controls the weather.",
  "A painter whose artwork comes to life.",
  "You find a notebook that answers any question you write in it.",
  "Describe a city that only exists during a thunderstorm.",
  "A character who can see the history of any object they touch.",
  "The moon shatters into a million pieces.",
  "You discover that your entire life has been a simulation.",
  "Write about a journey to the center of the earth.",
  "A tree that bears fruit which grants different abilities.",
  "A world where everyone has a predetermined lifespan.",
  "You wake up with the ability to speak every language in the world.",
  "Describe a secret garden hidden in the middle of a bustling city.",
  "A mysterious illness that causes people to slowly turn into crystal.",
  "A character who can travel through time, but only backwards.",
  "The discovery of a hidden civilization deep in the jungle.",
  "Write about a war between two ancient gods.",
  "A magical artifact that can manipulate reality.",
  "You find a hidden room in your house that you've never seen before.",
  "Describe a world where people communicate entirely through thoughts.",
  "A character who can control the elements.",
  "The sun suddenly disappears, plunging the world into darkness.",
  "Write about a journey across a vast, endless desert.",
  "A mysterious island that moves around the ocean.",
  "A character who is cursed with immortality.",
  "The discovery of a new, uncharted planet.",
  "Describe a city built entirely underwater.",
  "A magical creature that grants wishes, but at a terrible cost.",
  "You find a portal to another dimension in your basement.",
  "A world where people are divided into different factions based on their abilities.",
  "Write about a rebellion against a tyrannical government.",
  "A character who can shape-shift into any animal.",
  "The discovery of a cure for a deadly disease, but it has unexpected side effects.",
  "Describe a world where dreams can become reality.",
  "A magical forest where the trees can speak.",
  "You find a hidden treasure that has been lost for centuries.",
  "A character who is haunted by the ghosts of their past.",
  "Write about a journey to the edge of the universe.",
  "A mysterious cult that worships a dark deity.",
  "Describe a city that is entirely suspended in the sky.",
  "A magical sword that can cut through anything.",
  "You find a map that leads to a mythical land.",
  "A world where people can manipulate dreams.",
  "Write about a battle between good and evil.",
  "A character who is destined to save the world.",
  "The discovery of a hidden underground city.",
  "Describe a world where magic and technology coexist.",
  "A magical artifact that can bring the dead back to life.",
  "You find a hidden message in a famous painting.",
  "A character who can read minds.",
  "The discovery of a secret organization that controls the world.",
  "Write about a journey to find a mythical creature.",
  "A mysterious phenomenon that causes people to lose their memories.",
  "Describe a city that is entirely made of crystal.",
  "A magical ring that grants invisibility.",
  "You find a hidden doorway in the middle of a forest.",
  "A world where people are born with unique powers.",
  "Write about a quest to find a powerful artifact.",
  "A character who is cursed to wander the earth forever.",
  "The discovery of a hidden temple deep in the mountains.",
  "Describe a world where the laws of physics do not apply.",
  "A magical book that can change the past.",
  "You find a hidden message in a piece of music.",
  "A character who can control the minds of others.",
  "The discovery of a secret society of assassins.",
  "Write about a journey to a parallel universe.",
  "A mysterious disease that causes people to sleep forever.",
  "Describe a city that is entirely powered by magic.",
  "A magical staff that can summon the elements.",
  "You find a hidden message in a dream.",
  "A world where people can communicate with animals.",
  "Write about a battle for the fate of the world.",
  "A character who is half-human, half-monster.",
  "The discovery of a hidden island that is not on any map.",
  "Describe a world where people are immortal.",
  "A magical amulet that grants invulnerability.",
  "You find a hidden message in a piece of writing.",
  "A character who can control time.",
  "The discovery of a secret society of magicians.",
  "Write about a journey to a lost civilization."
];

export function getRandomPrompt(): string {
  const index = Math.floor(Math.random() * PROMPTS.length);
  return PROMPTS[index];
}
